slim

diff --git a/slim/Dockerfile b/slim/Dockerfile
--- a/slim/Dockerfile
+++ b/slim/Dockerfile
@@ -1,4 +1,6 @@
-FROM ai_ticket
+#FROM ai_ticket
+ARG OFFICIAL_PYTHON_IMAGE
+FROM ${OFFICIAL_PYTHON_IMAGE} 
 
 # Install browsers
 # Install utilities
@@ -13,24 +15,18 @@ ENV PIP_NO_CACHE_DIR=yes \
     POETRY_VIRTUALENVS_IN_PROJECT=0 \
     POETRY_NO_INTERACTION=1
 
-# Install and configure Poetry
-
-RUN curl -sSL https://install.python-poetry.org | python3 -
-RUN curl -sSL https://install.python-poetry.org | python3 -
 ENV PATH="$POETRY_HOME/bin:$PATH"
-RUN poetry config installer.max-workers 10
-
 
 ADD autogpts/autogpt /app/
 
 ADD ./benchmark /benchmark/
 
 WORKDIR /app
-RUN poetry run pip install /opt/ai-ticket
+#RUN poetry run pip install /opt/ai-ticket
 # RUN poetry install
 
 RUN poetry install --verbose ||echo some failed lets inspect
-RUN poetry install --verbose ||echo some failed lets inspect
+#RUN poetry install --verbose ||echo some failed lets inspect
 
 ENTRYPOINT ["poetry", "run", "autogpt", "--install-plugin-deps"]
 #ENTRYPOINT ["poetry", "install" ]
