Fix CI back (#342)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -155,7 +155,10 @@ jobs:
             pip install -r requirements.txt
             pip uninstall agbenchmark -y
           elif [ "$AGENT_NAME" == "mini-agi" ]; then
-            echo "test"
+            python -m venv venv
+            source venv/bin/activate
+            pip install -r requirements.txt
+            cp .env_example .env
           elif [ "$AGENT_NAME" == "smol-developer" ]; then
             python -m venv venv
             source venv/bin/activate
@@ -196,6 +199,24 @@ jobs:
 
 
           if [ "${GITHUB_EVENT_NAME}" == "pull_request" ] || [ "${{ github.event_name }}" == "push" ]; then            
+            set +e # Ignore non-zero exit codes and continue execution
+            ${prefix}agbenchmark start --maintain --mock
+            EXIT_CODE=$?
+            set -e  # Stop ignoring non-zero exit codes
+            # Check if the exit code was 5, and if so, exit with 0 instead
+            if [ $EXIT_CODE -eq 5 ]; then
+              echo "regression_tests.json is empty."
+            fi
+            ${prefix}agbenchmark start --mock
+            ${prefix}agbenchmark start --mock --category=retrieval
+            ${prefix}agbenchmark start --mock --category=interface
+            ${prefix}agbenchmark start --mock --category=code
+            ${prefix}agbenchmark start --mock --category=memory
+            ${prefix}agbenchmark start --mock --category=iterate
+            ${prefix}agbenchmark start --mock --suite TestReturnCode 
+            ${prefix}agbenchmark start --mock --suite TestRevenueRetrieval
+            ${prefix}agbenchmark start --test=TestWriteFile
+          
             cd ../..
             poetry install
             poetry run uvicorn server:app --reload &
