fix ci cassettes

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -102,15 +102,35 @@ jobs:
           git config user.email "github-actions@github.com"
           git config user.name "GitHub Actions"
           git commit -m "Add new cassettes"
-          echo "::set-output name=timestamp::$TIMESTAMP"
+          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
+      
 
       - name: Create PR
         id: create_pr
         uses: peter-evans/create-pull-request@v5
         with:
           commit-message: Update cassettes
-          branch: cassette-diff-PR${{ github.event.pull_request.number }}-${{ steps.stage_files.outputs.timestamp }}
-          title: "Update cassettes"
-          body: "This PR updates the cassettes."
+          branch: cassette-diff-PR${{ github.event.pull_request.number }}-${{ env.TIMESTAMP }}
+          title: "Update cassette-diff-PR${{ github.event.pull_request.number }}-${{ env.TIMESTAMP }}"
+          body: "This PR updates the cassettes. Please merge it."
 
 
+      - name: Check PR
+        run: |
+          echo "Pull Request Number - ${{ steps.create_pr.outputs.pull-request-number }}"
+          echo "Pull Request URL - ${{ steps.create_pr.outputs.pull-request-url }}"
+
+      - name: Comment PR URL in the current PR
+        if: ${{ steps.create_pr.outputs.pull-request-number }} != ''
+        uses: thollander/actions-comment-pull-request@v2
+        with:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          message: |
+            Please click [HERE](${{ steps.create_pr.outputs.pull-request-url }}) and merge this PR to update the cassettes.
+
+      - name: Fail if new PR created
+        run: |
+          if [[ "${{ steps.create_pr.outputs.pull-request-url }}" != "" ]]; then
+            echo "A new pull request for cassettes was created, failing workflow."
+            exit 1
+          fi
