Clarifications

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -37,14 +37,15 @@ jobs:
         with:
           python-version: ${{ env.min-python-version }}
 
-      - name: Set Date
-        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
+      - id: get_date
+        name: Get date
+        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
 
-      - name: Cache Python packages
+      - name: Set up Python dependency cache
         uses: actions/cache@v3
         with:
           path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ env.DATE }}
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ steps.get_date.outputs.date }}
 
       - name: Install dependencies
         run: |
@@ -90,7 +91,7 @@ jobs:
         python-version: ["3.10"]
 
     steps:
-      - name: Check out repository
+      - name: Checkout repository
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
@@ -98,12 +99,12 @@ jobs:
           repository: ${{ github.event.pull_request.head.repo.full_name }}
           submodules: true
 
-      - name: Setup git username and email
+      - name: Configure git user Auto-GPT-Bot
         run: |
           git config --global user.name "Auto-GPT-Bot"
           git config --global user.email "github-bot@agpt.co"
 
-      - name: Check out cassettes
+      - name: Checkout cassettes
         if: ${{ startsWith(github.event_name, 'pull_request') }}
         run: |
           cassette_branch="${{ github.event.pull_request.user.login }}-${{ github.event.pull_request.head.ref }}"
@@ -115,12 +116,14 @@ jobs:
 
             git checkout $cassette_branch
 
-            git merge --no-commit --strategy-option ours origin/${{ github.event.pull_request.base.ref }}
-            echo "Using cassettes from mirror branch, synced to upstream branch '${{ github.event.pull_request.base.ref }}' if no conflicts."
+            # Pick non-conflicting cassette updates from the base branch
+            git merge --no-commit --strategy-option=ours origin/${{ github.event.pull_request.base.ref }}
+            echo "Using cassettes from mirror branch '$cassette_branch'," \
+              "synced to upstream branch '${{ github.event.pull_request.base.ref }}'."
           else
             git checkout -b $cassette_branch
-            echo "Branch '$cassette_branch' does not exist in cassette submodule."\
-              "Using cassettes from ${{ github.event.pull_request.base.ref }}."
+            echo "Branch '$cassette_branch' does not exist in cassette submodule." \
+              "Using cassettes from '${{ github.event.pull_request.base.ref }}'."
           fi
 
       - name: Set up Python ${{ matrix.python-version }}
@@ -128,21 +131,22 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
 
-      - name: Set Date
-        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
+      - id: get_date
+        name: Get date
+        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
 
-      - name: Cache Python packages
+      - name: Set up Python dependency cache
         uses: actions/cache@v3
         with:
           path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ env.DATE }}
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ steps.get_date.outputs.date }}
 
-      - name: Install dependencies
+      - name: Install Python dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
-      - name: Run pytest tests with coverage
+      - name: Run pytest with coverage
         run: |
           pytest -n auto --cov=autogpt --cov-report term-missing --cov-branch --cov-report xml --cov-report term
           python tests/integration/challenges/utils/build_current_score.py
@@ -157,7 +161,8 @@ jobs:
 
       - id: setup_git_auth
         name: Set up git token authentication
-        if: always() && (startsWith(github.event_name, 'pull_request') || success())
+        # Cassettes may be pushed even when tests fail
+        if: success() || failure()
         run: |
           config_key="http.${{ github.server_url }}/.extraheader"
           base64_pat=$(echo -n "pat:${{ secrets.PAT_REVIEW }}" | base64 -w0)
@@ -186,7 +191,8 @@ jobs:
 
       - id: push_cassettes
         name: Push updated cassettes
-        if: always() && (startsWith(github.event_name, 'pull_request') || success())
+        # For pull requests, push updated cassettes even when tests fail
+        if: github.event_name == 'push' || success() || failure()
         run: |
           if [ "${{ startsWith(github.event_name, 'pull_request') }}" = "true" ]; then
             is_pull_request=true
